import localFont from "next/font/local";
import "./globals.css";

// Packages styles
import "swiper/css";
import "swiper/css/pagination";

const iranYekan = localFont({
  src: [
    {
      path: "./fonts/iranyekan/iranyekanwebthinfanum.woff",
      weight: "100",
    },
    {
      path: "./fonts/iranyekan/iranyekanweblightfanum.woff",
      weight: "200",
    },
    {
      path: "./fonts/iranyekan/iranyekanwebregularfanum.woff",
      weight: "300",
    },
    {
      path: "./fonts/iranyekan/iranyekanwebmediumfanum.woff",
      weight: "500",
    },
    {
      path: "./fonts/iranyekan/iranyekanwebboldfanum.woff",
      weight: "600",
    },
    {
      path: "./fonts/iranyekan/iranyekanwebextraboldfanum.woff",
      weight: "700",
    },
    {
      path: "./fonts/iranyekan/iranyekanwebblackfanum.woff",
      weight: "800",
    },
    {
      path: "./fonts/iranyekan/iranyekanwebextrablackfanum.woff",
      weight: "900",
    },
  ],
  variable: "--font-iran-yekan",
});

export const metadata = {
  title: "Auto Yadak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        className={`antialiased ${iranYekan.className} bg-[#F7F7F7]`}
        dir="rtl"
      >
        {children}
      </body>
    </html>
  );
}
